[package]
name = "fetches"
version = "0.1.0"
edition = "2024"

[dependencies]
ahqstore-types = "3.14.0"
paste = "1.0.15"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["macros", "rt", "rt-multi-thread"] }
